image: dukedesigncoach/testfx-runner

stages:
  - analyze
  - validate

checkstyle_analysis:
  stage: validate
  script:
    - mvn -version
    - mvn -U validate

sonar_analysis:
  stage: analyze
  script:
    - java -version
    - mvn -version
    - |
      mvn -X sonar:sonar \
      -Dsonar.host.url=http://coursework.cs.duke.edu:9002 \
      -Dsonar.java.binaries=. \
      -Dsonar.exclusions=**/*.xml,**/*.css,test/**
  tags:
    - sonarqube
  only:
    - master
